<img src="https://drive.google.com/uc?export=view&id=1hiCNHNWliU96ZuVD0BnzFxdbaYzNPUtI" width="1200"/>

-  Social Media and Contact
  - My SNS: [instagram](https://www.instagram.com/ringo_data/?igsh=MTlrdW4xMzZvNTBtdw%3D%3D), [github](https://github.com/Hyosun-Kim)
  - E-mail: hyosunkim00@gmail.com

---
Command + M A = Add a cell above (코드 셀 위에 삽입)  
Command + M B = Add a cell below (코드 셀 아래 삽입)  
Command + M D = Delete a cell (셀 지우기)  
Command + M Y = Change cell to code (코드 셀로 변경)  
Command + M M = Change cell to markdown (마크다운 셀로 변경)   
Command + M Z = Undo (실행 취소)
<!-- -->

---

## How to connect to the Google Drive in Colab

> [NOTION](https://www.notion.so/Connect-with-Google-Drive-46abe50d2758444d8a5dca59f0176b84?pvs=4)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# pd.read_csv(): Load the csv data
```python
import pandas as pd
df = pd.read_csv('path/file.csv')
```
We are gonna import the pandas as name of the "pd" and bring the file through "read_csv".

## pd.read_csv

In [ ]:
# how to load iris
# Right-clich the iris file and copy path(경로복사)
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab(python+DA)/iris.csv의 사본')

In [ ]:
# what's the type of df?
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
type(df)
#이 데이터 셋은 데이터 프레임으로 들어와있는 걸 알 수 있음.
#데이터 셋을 불러오면 자동으로 데이터프레임 형태로 들어옴.

pandas.core.frame.DataFrame

###실무에서 사용하는 99퍼의 데이터 분석할 때 쓰는 파일은 csv 파일이다.
####comma seperated value = csv

# Tabular Data 와 Data type

## Tabular Data

<img src="https://i.ibb.co/0BY3syD/Tabular-Data-explain-1.png" width="500"/>


- 행 (Row): 데이터 테이블에서 가로 방향의 데이터 집합. 하나의 행은 특정 `레코드`.

- 열 (Column): 데이터 테이블에서 세로 방향의 데이터 집합. 하나의 열은 특정 `속성`.

- 값 (Value): `행과 열이 교차`하는 지점에 위치한 개별 데이터.

- 인덱스 (Index): `행을 구별`하는 데 사용되는 고유한 식별자.

In [ ]:
#  .shape: 행, 열 수 표시.
#  .columns: 열 이름 나열.
#  .values: 데이터를 배열로 반환.
#  .index: 행 인덱스 반환.

In [ ]:
df.shape
#row가 150개 colum이 6개 있다는 뜻

(150, 6)

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
df.values

array([[1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [22, 5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [23, 4.6, 3.6, 1.0, 0.2, 'Iris-setosa'],
       [24, 5.1, 3.3, 1.7, 0.5, 'Iris-setosa'],
       [25, 4.8, 3.4, 1.9, 0.2, 'Iris-setosa'],
       [26, 5.0, 3.0, 1.6, 0.2, 'Iris-setosa'],
       [27, 5.0, 3.4, 1.6, 0.4, 'Iris-setosa'],
       [28, 5.2, 3.5, 1.5, 0.2, 'Iris-setosa'],
       [29, 5.2, 3.4, 1.4, 0.2, 'Iris-setosa'],
       [30, 4.7, 3.2, 1.6, 0.2, 'Iris-setosa'],
       [31, 4.8, 3.1, 1.6, 0.2, 'Iris-setosa'],
       [32, 5.4, 3.4, 1.5, 0.4, 'Iris-setosa'],
       [33, 5.2, 4.1, 1.5, 0.1, 'Iris-setosa'],
       [34, 5.5, 4.2, 1.4, 0.2, 'Iris-setosa'],
       [35, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [36, 5.0, 3.2, 1.2, 0.2, 'Iris-setosa'],
       [37, 5.5, 3.5, 1.3, 0.2, 'Iris-setosa'],
       [38, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [39, 4.4, 3.0, 1.3, 0.2, 'Iris-setosa'],
       [40, 5.1, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [41, 5.0, 3.5, 1.3, 0.3, 'Iris-setosa'],
       [42, 4.5, 2.3, 1.3, 0.3, 'Iris-setosa'],
       [43, 4.4, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [44, 5.0, 3.5, 1.6, 0.6, 'Iris-setosa'],
       [45, 5.1, 3.8, 1.9, 0.4, 'Iris-setosa'],
       [46, 4.8, 3.0, 1.4, 0.3, 'Iris-setosa'],
       [47, 5.1, 3.8, 1.6, 0.2, 'Iris-setosa'],
       [48, 4.6, 3.2, 1.4, 0.2, 'Iris-setosa'],
       [49, 5.3, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [50, 5.0, 3.3, 1.4, 0.2, 'Iris-setosa'],
       [51, 7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'],
       [52, 6.4, 3.2, 4.5, 1.5, 'Iris-versicolor'],
       [53, 6.9, 3.1, 4.9, 1.5, 'Iris-versicolor'],
       [54, 5.5, 2.3, 4.0, 1.3, 'Iris-versicolor'],
       [55, 6.5, 2.8, 4.6, 1.5, 'Iris-versicolor'],
       [56, 5.7, 2.8, 4.5, 1.3, 'Iris-versicolor'],
       [57, 6.3, 3.3, 4.7, 1.6, 'Iris-versicolor'],
       [58, 4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'],
       [59, 6.6, 2.9, 4.6, 1.3, 'Iris-versicolor'],
       [60, 5.2, 2.7, 3.9, 1.4, 'Iris-versicolor'],
       [61, 5.0, 2.0, 3.5, 1.0, 'Iris-versicolor'],
       [62, 5.9, 3.0, 4.2, 1.5, 'Iris-versicolor'],
       [63, 6.0, 2.2, 4.0, 1.0, 'Iris-versicolor'],
       [64, 6.1, 2.9, 4.7, 1.4, 'Iris-versicolor'],
       [65, 5.6, 2.9, 3.6, 1.3, 'Iris-versicolor'],
       [66, 6.7, 3.1, 4.4, 1.4, 'Iris-versicolor'],
       [67, 5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [68, 5.8, 2.7, 4.1, 1.0, 'Iris-versicolor'],
       [69, 6.2, 2.2, 4.5, 1.5, 'Iris-versicolor'],
       [70, 5.6, 2.5, 3.9, 1.1, 'Iris-versicolor'],
       [71, 5.9, 3.2, 4.8, 1.8, 'Iris-versicolor'],
       [72, 6.1, 2.8, 4.0, 1.3, 'Iris-versicolor'],
       [73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'],
       [74, 6.1, 2.8, 4.7, 1.2, 'Iris-versicolor'],
       [75, 6.4, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [76, 6.6, 3.0, 4.4, 1.4, 'Iris-versicolor'],
       [77, 6.8, 2.8, 4.8, 1.4, 'Iris-versicolor'],
       [78, 6.7, 3.0, 5.0, 1.7, 'Iris-versicolor'],
       [79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'],
       [80, 5.7, 2.6, 3.5, 1.0, 'Iris-versicolor'],
       [81, 5.5, 2.4, 3.8, 1.1, 'Iris-versicolor'],
       [82, 5.5, 2.4, 3.7, 1.0, 'Iris-versicolor'],
       [83, 5.8, 2.7, 3.9, 1.2, 'Iris-versicolor'],
       [84, 6.0, 2.7, 5.1, 1.6, 'Iris-versicolor'],
       [85, 5.4, 3.0, 4.5, 1.5, 'Iris-versicolor'],
       [86, 6.0, 3.4, 4.5, 1.6, 'Iris-versicolor'],
       [87, 6.7, 3.1, 4.7, 1.5, 'Iris-versicolor'],
       [88, 6.3, 2.3, 4.4, 1.3, 'Iris-versicolor'],
       [89, 5.6, 3.0, 4.1, 1.3, 'Iris-versicolor'],
       [90, 5.5, 2.5, 4.0, 1.3, 'Iris-versicolor'],
       [91, 5.5, 2.6, 4.4, 1.2, 'Iris-versicolor'],
       [92, 6.1, 3.0, 4.6, 1.4, 'Iris-versicolor'],
       [93, 5.8, 2.6, 4.0, 1.2, 'Iris-versicolor'],
       [94, 5.0, 2.3, 3.3, 1.0, 'Iris-versicolor'],
       [95, 5.6, 2.7, 4.2, 1.3, 'Iris-versicolor'],
       [96, 5.7, 3.0, 4.2, 1.2, 'Iris-versicolor'],
       [97, 5.7, 2.9, 4.2, 1.3, 'Iris-versicolor'],
       [98, 6.2, 2.9, 4.3, 1.3, 'Iris-versicolor'],
       [99, 5.1, 2.5, 3.0, 1.1, 'Iris-versicolor'],
       [100, 5.7, 2.8, 4.1, 1.3, 'Iris-versicolor'],
       [101, 6.3, 3.3, 6.0, 2.5, 'Iris-virginica'],
       [102, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [103, 7.1, 3.0, 5.9, 2.1, 'Iris-virginica'],
       [104, 6.3, 2.9, 5.6, 1.8, 'Iris-virginica'],
       [105, 6.5, 3.0, 5.8, 2.2, 'Iris-virginica'],
       [106, 7.6, 3.0, 6.6, 2.1, 'Iris-virginica'],
       [107, 4.9, 2.5, 4.5, 1.7, 'Iris-virginica'],
       [108, 7.3, 2.9, 6.3, 1.8, 'Iris-virginica'],
       [109, 6.7, 2.5, 5.8, 1.8, 'Iris-virginica'],
       [110, 7.2, 3.6, 6.1, 2.5, 'Iris-virginica'],
       [111, 6.5, 3.2, 5.1, 2.0, 'Iris-virginica'],
       [112, 6.4, 2.7, 5.3, 1.9, 'Iris-virginica'],
       [113, 6.8, 3.0, 5.5, 2.1, 'Iris-virginica'],
       [114, 5.7, 2.5, 5.0, 2.0, 'Iris-virginica'],
       [115, 5.8, 2.8, 5.1, 2.4, 'Iris-virginica'],
       [116, 6.4, 3.2, 5.3, 2.3, 'Iris-virginica'],
       [117, 6.5, 3.0, 5.5, 1.8, 'Iris-virginica'],
       [118, 7.7, 3.8, 6.7, 2.2, 'Iris-virginica'],
       [119, 7.7, 2.6, 6.9, 2.3, 'Iris-virginica'],
       [120, 6.0, 2.2, 5.0, 1.5, 'Iris-virginica'],
       [121, 6.9, 3.2, 5.7, 2.3, 'Iris-virginica'],
       [122, 5.6, 2.8, 4.9, 2.0, 'Iris-virginica'],
       [123, 7.7, 2.8, 6.7, 2.0, 'Iris-virginica'],
       [124, 6.3, 2.7, 4.9, 1.8, 'Iris-virginica'],
       [125, 6.7, 3.3, 5.7, 2.1, 'Iris-virginica'],
       [126, 7.2, 3.2, 6.0, 1.8, 'Iris-virginica'],
       [127, 6.2, 2.8, 4.8, 1.8, 'Iris-virginica'],
       [128, 6.1, 3.0, 4.9, 1.8, 'Iris-virginica'],
       [129, 6.4, 2.8, 5.6, 2.1, 'Iris-virginica'],
       [130, 7.2, 3.0, 5.8, 1.6, 'Iris-virginica'],
       [131, 7.4, 2.8, 6.1, 1.9, 'Iris-virginica'],
       [132, 7.9, 3.8, 6.4, 2.0, 'Iris-virginica'],
       [133, 6.4, 2.8, 5.6, 2.2, 'Iris-virginica'],
       [134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'],
       [135, 6.1, 2.6, 5.6, 1.4, 'Iris-virginica'],
       [136, 7.7, 3.0, 6.1, 2.3, 'Iris-virginica'],
       [137, 6.3, 3.4, 5.6, 2.4, 'Iris-virginica'],
       [138, 6.4, 3.1, 5.5, 1.8, 'Iris-virginica'],
       [139, 6.0, 3.0, 4.8, 1.8, 'Iris-virginica'],
       [140, 6.9, 3.1, 5.4, 2.1, 'Iris-virginica'],
       [141, 6.7, 3.1, 5.6, 2.4, 'Iris-virginica'],
       [142, 6.9, 3.1, 5.1, 2.3, 'Iris-virginica'],
       [143, 5.8, 2.7, 5.1, 1.9, 'Iris-virginica'],
       [144, 6.8, 3.2, 5.9, 2.3, 'Iris-virginica'],
       [145, 6.7, 3.3, 5.7, 2.5, 'Iris-virginica'],
       [146, 6.7, 3.0, 5.2, 2.3, 'Iris-virginica'],
       [147, 6.3, 2.5, 5.0, 1.9, 'Iris-virginica'],
       [148, 6.5, 3.0, 5.2, 2.0, 'Iris-virginica'],
       [149, 6.2, 3.4, 5.4, 2.3, 'Iris-virginica'],
       [150, 5.9, 3.0, 5.1, 1.8, 'Iris-virginica']], dtype=object)

In [ ]:
df.index
#0부터 150까지 1씩 올라가면서 있다는 뜻

RangeIndex(start=0, stop=150, step=1)

## Data Type

1. **Categorical Data (범주형 데이터):** 제한된 수의 `범주`로 나눌 수 있는 데이터. 예시로는 성별, 혈액형, 학년이 있음
    
2. **Numeric Data (수치 데이터):** 수치로 표현되며 `계산이 가능`한 데이터.
    
    - **Binary Data (이진 데이터):** `'0'과 '1'로만` 구성된 데이터. 예시로는 합격 여부, 물품 구매 여부 등이 있음, 이는 경우에 따라 범주형 데이터로도 분류.
    - **Ratio Data (비율 데이터):** 값들 사이의 `비율 비교`가 가능한 데이터. 예시로는 키, 몸무게, 가격

In [ ]:
# realistic_binary_data.csv

# Exercise
- gg

1. pandas 라이브러리를 활용하여 titanic.csv 파일을 불러오세요

In [ ]:
import pandas as pd
pd.read_csv('/content/drive/MyDrive/Colab(python+DA)/titanic.csv의 사본')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

---

<img src="https://drive.google.com/uc?export=view&id=1hiCNHNWliU96ZuVD0BnzFxdbaYzNPUtI" width="1200"/>