<img src="https://drive.google.com/uc?export=view&id=1hiCNHNWliU96ZuVD0BnzFxdbaYzNPUtI" width="1200"/>

-  Social Media and Contact
  - My SNS: [instagram](https://www.instagram.com/ringo_data/?igsh=MTlrdW4xMzZvNTBtdw%3D%3D), [github](https://github.com/Hyosun-Kim)
  - E-mail: hyosunkim00@gmail.com

---
Command + M A = Add a cell above (코드 셀 위에 삽입)  
Command + M B = Add a cell below (코드 셀 아래 삽입)  
Command + M D = Delete a cell (셀 지우기)  
Command + M Y = Change cell to code (코드 셀로 변경)  
Command + M M = Change cell to markdown (마크다운 셀로 변경)   
Command + M Z = Undo (실행 취소)
<!-- -->

---

# to_datatime
- 시간 관련 데이터를 Python의 datetime 객체로 변환
- 다양한 형태의 날짜 및 시간 데이터를 처리할 수 있음
- date 와 time 형태의 데이터는 문자열로 인식하는 경우가 많음.
```python
pd.to_datetime(df['col'])
```

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab(python+DA)/taxis.csv의 사본')

In [ ]:
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
#이 컬럼의 성격에 대해서 알아보자
df.info()
#pickup 이랑 dropoff가 object type으로 되어있는 것을 알 수 있음.
#datetime으로 바꿔주는 작업을 할 거임 왜하는거냐 아직 나도 모름 ^^

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   object
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: float64(5), int64(1), object(8)
memory usage: 703.7+ KB

In [ ]:
df['pickup'] = pd.to_datetime(df.pickup)
#보면 dtype이 datetime으로 바뀐 것을 알 수 있음
#여기서 pickup이라는 컬럼에 덮어써주기 위해서 pd.to_datetime(df.pickup) 앞에 df['pickup'] = pd.to_datetime(df.pickup) 이렇게 할거임

In [ ]:
df.info()
#pickup의 Dtype이 datetime으로 바뀐 것을 볼 수 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 703.7+ KB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# to_period
- datetime으로 바꾼 것을 사용해서 주기를 변경하고, 원하는 형태로 데이터 포맷을 바꾸는 것을 할 것임
- 날짜/시간 데이터를 주어진 주기('M', 'W', 'Y' 등)로 변환
- dt는 날짜를 변경하는 method들이 들어있는 서랍이라고 생각하면됨
```python
 df['col'].dt.to_period('period').dt.strftime('%Y-%m-%d')
# to_period('period') : Daily(D), Weekly(W), Monthly(M), Yearly(Y) 등 주기로 나타냄
# dt.strftime('%Y-%m-%d') : 'YYYY-MM-DD' 형태로 표시함
 ```

In [ ]:
df.head()
df.info()
#pickup은 datetime으로 들어가 있고, dropoff는 object로 들어가있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(7)
memory usage: 703.7+ KB

In [ ]:
df.pickup
#Weekly로 나타내기
df.pickup.dt.to_period('W').dt.strftime('%Y-%m-%d')
#pickup 으로 했을 때는 바뀌는데 아마 dropoff를 넣어서 돌린다면 안돌아감 왜냐하면 dropoff는 datetime 형태로 안바꿨기 때문.
#따라서 datetime으로 바꾸는 과정이 필요한거

#dt.to_timestamp() -> 시작 날짜를 보여줌
#dt.strftime('%Y-%m-%d') -> 끝나는 날짜를 보여줌

0       2019-03-24
1       2019-03-10
2       2019-03-31
3       2019-03-10
4       2019-03-31
           ...
6428    2019-03-31
6429    2019-03-31
6430    2019-03-24
6431    2019-03-10
6432    2019-03-17
Name: pickup, Length: 6433, dtype: object

In [ ]:
#끝나는 날짜를 기준으로 보여주는 column 생성
df['pickup_w'] = df.pickup.dt.to_period('W').dt.strftime('%Y-%m-%d')

In [ ]:
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,pickup_w
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,2019-03-24
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan,2019-03-10
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan,2019-03-31
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan,2019-03-10
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan,2019-03-31

In [ ]:
df.info()
#pickup_w 를 확인해보면 잘 생성이 되었고, type을 보면 object로 생성되어있는 것을 알 수 있음
#pickup_w 는 일단 날짜 관련 전처리를 할 생각이 없기 때문에 그냥 놔두도록 하겠음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   object
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
 14  pickup_w         6433 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(1), object(8)
memory usage: 754.0+ KB

# parse_dates
날짜 관련 전처리를 위한 또 다른 방법
```python
read_csv( ,parse_dates = ['col1','col2'...])
```

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab(python+DA)/taxis.csv의 사본'
                  , parse_dates = [ 'pickup', 'dropoff']
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

# timedelta
- 두 날짜 또는 시간 사이의 차이를 나타내는 데 사용
```python
df['duration'] = (df['end'] - df['start']).dt.total_seconds()
```

In [ ]:
df.dropoff - df.pickup
#timedelta라는 새로운 타입이 나옴, 편하게 보기 위해서 바꿔줄거임 ㄱㄷ
(df.dropoff - df.pickup).dt.total_seconds() #초로 나타내고 이것을 분 단위로 바꿔줄 거임(택시는 분 단위로 보는게 더 편해서)
(df.dropoff - df.pickup).dt.total_seconds()/60 #60으로 나눠주면 분단위가 나오겠죠?

0        6.250000
1        7.083333
2        7.400000
3       25.866667
4        9.533333
          ...
6428     3.566667
6429    56.383333
6430    19.116667
6431     5.066667
6432    16.666667
Length: 6433, dtype: float64

In [ ]:
#이것을 다시 column으로 만들어서 dataframe에 넣어주도록 하겠음
df['minute_pickup_to_dropoff'] = (df.dropoff - df.pickup).dt.total_seconds()/60
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pickup                    6433 non-null   datetime64[ns]
 1   dropoff                   6433 non-null   datetime64[ns]
 2   passengers                6433 non-null   int64
 3   distance                  6433 non-null   float64
 4   fare                      6433 non-null   float64
 5   tip                       6433 non-null   float64
 6   tolls                     6433 non-null   float64
 7   total                     6433 non-null   float64
 8   color                     6433 non-null   object
 9   payment                   6389 non-null   object
 10  pickup_zone               6407 non-null   object
 11  dropoff_zone              6388 non-null   object
 12  pickup_borough            6407 non-null   object
 13  dropoff_borough           6388 non-null   object
 14  minute_pickup_to_dropoff  6433 non-null   float64
dtypes: datetime64[ns](2), float64(6), int64(1), object(6)
memory usage: 754.0+ KB

# Exercise

```python
# 데이터프레임 생성을 위한 딕셔너리
data = {
    'start': ['2021-01-01 10:00', '2021-01-02 11:30', '2021-01-03 09:45', '2021-01-04 15:00', '2021-01-05 18:20'],
    'end': ['2021-01-01 15:30', '2021-01-02 01:00', '2021-01-04 10:15', '2021-01-05 15:30', '2021-08-05 18:50']
}
# 데이터프레임 생성
df = pd.DataFrame(data)
df.info()
```

start 열과 end 열이 있는 DataFrame df가 주어져요.
1. for 루프를 사용하여 DataFrame의 'start' 열과 'end' 열을 datetime 유형으로 변환하십시오.
2. start에서 end까지의 시간 차이를 시간 단위로 계산하십시오. 시간 이하 단위의 차이는 소수점으로 표시하십시오.
3. 'end' 열의 날짜들을 주 단위('W')로 변환하고, 이를 'yyyy-mm-dd' 형태의 문자열로 표현하십시오.

In [ ]:
#for 루프를 사용하여 DataFrame의 'start' 열과 'end' 열을 datetime 유형으로 변환하십시오.
# 데이터프레임 생성을 위한 딕셔너리
data = {
  'start': ['2021-01-01 10:00', '2021-01-02 11:30', '2021-01-03 09:45', '2021-01-04 15:00', '2021-01-05 18:20'],
  'end': ['2021-01-01 15:30', '2021-01-02 01:00', '2021-01-04 10:15', '2021-01-05 15:30', '2021-08-05 18:50']
}
# 데이터프레임 생성
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   start   5 non-null      object
 1   end     5 non-null      object
dtypes: object(2)
memory usage: 208.0+ bytes

In [ ]:
pd.to_datetime(df.start)
#datetime으로 바꿈 but datetime으로 바꾼걸 저장해야되기 때문에 기존 데이터에 덮어씌우는 작업을 할 예정
df['start'] = pd.to_datetime(df.start)
df.info()
#여기서 우리가 처리해준거는 start만 datetime 형태로 처리해줬기 때문에 end도 for 루프를 통해서 처리해줄거임.
#columns 한 두개일 때는 직접 처리해줘도 되지만 엄청 많을 때는 for loop를 통해서 처리하는게 효율적임.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   start   5 non-null      datetime64[ns]
 1   end     5 non-null      object
dtypes: datetime64[ns](1), object(1)
memory usage: 208.0+ bytes

In [ ]:
col = df.columns
col
for i in col:
  df[i] = pd.to_datetime(df[i])
#i 라는 변수로 가져와서 모든 colums을 바꿔줄 수 있게 만들어주는거임.

#  df[pickup] = pd.to_datetime(df.pickup)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   start   5 non-null      datetime64[ns]
 1   end     5 non-null      datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 208.0 bytes

In [ ]:
#start에서 end까지의 시간 차이를 시간 단위로 계산하십시오. 시간 이하 단위의 차이는 소수점으로 표시
(df['end'] - df['start']).dt.total_seconds()/3600

0       5.5
1     -10.5
2      24.5
3      24.5
4    5088.5
dtype: float64

In [ ]:
#'end' 열의 날짜들을 주 단위('W')로 변환하고, 이를 'yyyy-mm-dd' 형태의 문자열로 표현

In [ ]:
df['end_weekly'] = df['end'].dt.to_period('W').dt.strftime('%Y-%m-%d')

In [ ]:
df

                start                 end  end_weekly
0 2021-01-01 10:00:00 2021-01-01 15:30:00  2021-01-03
1 2021-01-02 11:30:00 2021-01-02 01:00:00  2021-01-03
2 2021-01-03 09:45:00 2021-01-04 10:15:00  2021-01-10
3 2021-01-04 15:00:00 2021-01-05 15:30:00  2021-01-10
4 2021-01-05 18:20:00 2021-08-05 18:50:00  2021-08-08

---
<img src="https://drive.google.com/uc?export=view&id=1hiCNHNWliU96ZuVD0BnzFxdbaYzNPUtI" width="1200"/>